version: '3.9'
services:
  # === Infraestructura AWS
  infra_deployer:
    build: # Allows to build an image from local Dockerfile.
      context: infra
      dockerfile: Dockerfile
    container_name: infra_deployer
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./shared:/shared
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    #working_dir: /app/infra
    #command: ["bash", "deploy_all.sh"]
    networks:
      - micro_net

  # === Bases de datos PostgreSQL ===
  db_authentication:
    image: postgres:16.1
    container_name: db_authentication
    restart: always
    environment:
        DB_HOST: db_authentication
        DB_PORT: 5432
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: db_authentication
        POSTGRES_DB: postgres
    ports:
      - "5434:5432"          # puerto expuesto en tu host
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./local-databases/db-authentication/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql:ro
      - ./local-databases/db-authentication/sql/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro_net

  db_loanapplications: #select * from credi_ya.loan_applications;
    image: postgres:16.1
    container_name: db_loanapplications
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: db_loanapplications
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - loan_db_data:/var/lib/postgresql/data
      - ./local-databases/db-loan-application/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql:ro
      - ./local-databases/db-loan-application/sql/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro_net

  # === PgAdmin opcional ===
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "81:80"
    depends_on:
      - db_authentication
      - db_loanapplications
    networks:
      - micro_net

  # === Microservicio Autenticación ===
  ms_authentication:
    build:
      context: https://github.com/jaimebp07/pragma-ms-authentication.git#HU5
      #context: ./pragma-ms-authentication
      dockerfile: Dockerfile
    container_name: ms_authentication
    depends_on:
      - db_authentication
      - infra_deployer
    environment:
        SPRING_PROFILES_ACTIVE: docker
        DB_HOST: db_authentication
        DB_PORT: 5432
        DB_NAME: postgres
        DB_SCHEMA: credi_ya
        DB_USER: admin
        DB_PASSWORD: db_authentication
        SPRING_DATASOURCE_URL: jdbc:postgresql://db_authentication:5432/postgres
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: db_authentication
    ports:
      - "8080:8080"
    networks:
      - micro_net

  # === Microservicio Solicitudes ===
  ms_loanapplications:
    build:
      context: https://github.com/jaimebp07/pragma-ms-loan-application.git#HU5
      #context: ./pragma-ms-loan-application
      dockerfile: Dockerfile
    container_name: ms_loanapplications
    depends_on:
      - db_loanapplications
      - ms_authentication
      - infra_deployer
    environment:
        SPRING_PROFILES_ACTIVE: docker
        DB_HOST: db_loanapplications
        DB_PORT: 5432
        DB_NAME: postgres
        DB_USER: admin
        DB_PASSWORD: db_loanapplications
        SPRING_DATASOURCE_URL: jdbc:postgresql://db_loanapplications:5432/postgres
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: db_loanapplications
        AUTHENTICATION_URL: http://ms_authentication:8080

    ports:
      - "8082:8082"
    networks:
      - micro_net

volumes:
  auth_db_data:
  loan_db_data:

networks:
  micro_net:
    driver: bridge
